apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: gosty-apiserver

          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

