apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gosty-fileserver
  namespace: gosty

spec:
  template:
    spec:
      containers:
        - name: gosty-fileserver
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "128m"
              memory: "256Mi"
