resources:
  - ../../gosty


patches:

  #APISERVER
  - target:
      kind: Deployment
      name: gosty-apiserver
    path: apiserver-deployment.yaml

  - target:
      kind: Service
      name: gosty-apiserver
    path: apiserver-service.yaml
  #WEB
  - target:
      kind: Deployment
      name: gosty-web
    path: web-deployment.yaml

  - target:
      kind: Service
      name: gosty-web
    path: web-service.yaml
  #FILESERVER
  - target:
      kind: StatefulSet
      name: gosty-fileserver
    path: fileserver-deployment.yaml

  - target:
      kind: Service
      name: gosty-fileserver
    path: fileserver-service.yaml
  #WORKER
  - target:
      kind: Deployment
      name: gosty-worker
    path: worker-deployment.yaml