apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-web
  namespace: gosty

spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gosty-web
          resources:
            requests:
              cpu: "20m"
              memory: "50Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"

#          volumeMounts:
#            - mountPath: /etc/nginx/templates/
#              name: gosty-config
#              readOnly: true
#
#      volumes:
#        - name: gosty-config
#          configMap:
#            name: gosty-config
#            items:
#              - key: default.conf.template
#                path: default.conf.template
