apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-web
  namespace: gosty

spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: gosty-web
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"