apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-worker
  namespace: gosty

spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: gosty-worker
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1.5"
              memory: "1.5Gi"

