apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  annotations:
    linkerd.io/inject: enabled
  namespace: fluentd-monitoring
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: vm-max-fix
          image: k8s.gcr.io/busybox
          command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: elasticsearch:7.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          env:
            - name: node.name
              value: "elasticsearch"
            - name: cluster.initial_master_nodes
              value: "elasticsearch"
            - name: bootstrap.memory_lock
              value: "false"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: fluentd-monitoring
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: http
      port: 9200
      targetPort: 9200