database:
  uri: "mongodb://username:password@localhost:27017/gosty?authSource=admin"
  database: "gosty"
  timeout: 2

server:
  host: "localhost"
  port: "8000"

#message broker
#configuration on docker compose
#mb: "amqp://username:password@localhost:5672/"

#configuration on kubernetes
mb: "amqp://username:password@192.168.49.2:31672"

hostname: "WORKER_DEV"

#file server
fs_host: "http://localhost:8001"