version: '3.7'


services:
  web:
    image: localhost:5000/gosty-web
    restart: always
    ports:
      - "8082:80"

  apiserver:
    image: localhost:5000/gosty-apiserver
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      PORT: 8000

      MONGODB_SERVICE_HOST: mongo
      MONGODB_SERVICE_PORT: 27017
      MONGODB_USERNAME: username
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: gosty
      MONGODB_TIMEOUT: 2

      RABBIT_RABBITMQ_SERVICE_HOST: rabbitmq
      RABBIT_RABBITMQ_SERVICE_PORT: 5672
      RABBITMQ_USERNAME: username
      RABBITMQ_PASSWORD: password

      GOSTY_FILESERVER_SERVICE_HOST: fileserver
      GOSTY_FILESERVER_SERVICE_PORT: 8081

  worker:
    image: localhost:5000/gosty-worker
    restart: always
    #    mem_limit: 4096M
    #    cpu_quota: 4000
    #    deploy:
    #      resources:
    #        limits:
    #          cpus: '0.25'
    #          memory: 4096M
    #        reservations:
    #          cpus: '0.125'
    #          memory: 20M
    environment:
      RABBIT_RABBITMQ_SERVICE_HOST: rabbitmq
      RABBIT_RABBITMQ_SERVICE_PORT: 5672
      RABBITMQ_USERNAME: username
      RABBITMQ_PASSWORD: password

      GOSTY_FILESERVER_SERVICE_HOST: fileserver
      GOSTY_FILESERVER_SERVICE_PORT: 8081

  fileserver:
    image: localhost:5000/gosty-fileserver
    restart: always
    volumes:
      - ./storage:/app/storage/
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      PORT: "8081"

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gosty
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - mongo-volume:/data/db

  rabbitmq:
    image: rabbitmq:3.8.12-management-alpine
    volumes:
      - rabbitmq-volume-etc:/etc/rabbitmq/
      - rabbitmq-volume-data:/var/lib/rabbitmq/
      - rabbitmq-volume-logs:/var/log/rabbitmq/
#      - rabbitmq-volume-enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq-volume-etc:
  rabbitmq-volume-data:
  rabbitmq-volume-logs:
#  rabbitmq-volume-enables_plugins:
  mongo-volume:
