version: '3.7'
services:
#  pg:
#    image: library/postgres:13.1-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 'password'
#      POSTGRES_DB: 'gosty'
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./.docker/db:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gosty
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
    volumes:
      - ./.docker/mongo:/data/db

#  nginx:
#    build:
#      context: ./docker/nginx/
#    restart: always
#    volumes:
#      - ./.docker/nginx/fileserver:/tmp/nginx_upload/
#      - ./docker/nginx/nginx_upload.default.conf:/etc/nginx/conf.d/nginx_upload.default.conf
#    ports:
#    - "8001:80"

  rabbitmq:
    image: rabbitmq:3.8.12-management-alpine
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      - ./.docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"