version: '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gosty'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db:/var/lib/mysql

  nginx:
    image: nginx:1.19.6-alpine
    restart: always
    volumes:
      - ./docker/nginx/storage:/media/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8001:80"

  rabbitmq:
    image: rabbitmq:3.8.12-management-alpine
    volumes:
      - ./docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./docker/rabbitmq/logs/:/var/log/rabbitmq/
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"