version: '3.7'
services:
#  pg:
#    image: library/postgres:13.1-alpine
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: 'password'
#      POSTGRES_DB: 'gosty'
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./.docker/db:/var/lib/postgresql/data

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gosty
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
    volumes:
      - mongo-volume:/data/db

  rabbitmq:
    image: rabbitmq:3.8.12-management-alpine
    volumes:
      - rabbitmq-volume-etc:/etc/rabbitmq/
      - rabbitmq-volume-data:/var/lib/rabbitmq/
      - rabbitmq-volume-logs:/var/log/rabbitmq/
#      - rabbitmq-volume-enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq-volume-etc:
  rabbitmq-volume-data:
  rabbitmq-volume-logs:
#  rabbitmq-volume-enables_plugins:
  mongo-volume: