apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gosty-apiserver
  name: gosty-apiserver
  namespace: gosty
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: gosty-apiserver

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-memory-request: 50Mi
        config.linkerd.io/proxy-memory-limit: 256Mi
        config.linkerd.io/proxy-cpu-request: 50m
        config.linkerd.io/proxy-cpu-limit: 256m
      labels:
        app: gosty-apiserver

    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: topology.kubernetes.io/hostname
              weight: 100

      terminationGracePeriodSeconds: 5

      containers:
        - image: luqmansen/gosty-apiserver:latest
          name: gosty-apiserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gosty-config

          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            timeoutSeconds: 3
            failureThreshold: 5
            initialDelaySeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            timeoutSeconds: 3
            failureThreshold: 5
            initialDelaySeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  type: ClusterIP
  selector:
    app: gosty-apiserver
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8000

    - protocol: TCP
      port: 8089
      name: pprof
      targetPort: 8089

    - protocol: TCP
      port: 8086
      name: healthcheck
      targetPort: 8086