apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: gosty
  name: gosty-fileserver-localstorage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gosty-fileserver-volume
  namespace: gosty
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gosty-fileserver-localstorage
  local:
    path: /home/docker/fileserver-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gosty-fileserver-volume-claim
  namespace: gosty
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gosty-fileserver-localstorage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
