apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: apiserver-pod-kill
  namespace: gosty
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - gosty
    labelSelectors:
      app: gosty-apiserver
  scheduler:
    cron: '@every 60s'
  action: pod-kill
  mode: one
  value: ''
  containerName: ''
  gracePeriod: 0
