apiVersion: v1
kind: Namespace
metadata:
  name: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/name: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017