apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gosty-apiserver
  name: gosty-apiserver
  namespace: gosty
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gosty-apiserver
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-apiserver
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: gosty-config
        image: 10.98.241.154/gosty-apiserver:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /live
            port: 8086
          initialDelaySeconds: 5
        name: gosty-apiserver
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /ready
            port: 8086
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: gosty-apiserver
  type: ClusterIP
---
