apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-apiserver
  namespace: gosty
  labels:
    app: gosty-apiserver
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gosty-apiserver
  template:
    metadata:
      labels:
        app: gosty-apiserver
    spec:
      containers:
        - name: gosty-apiserver
          image: 10.109.191.7/gosty-apiserver:latest
          envFrom:
            - configMapRef:
                name: gosty-config
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  type: ClusterIP
  selector:
    app: gosty-apiserver
  ports:
    - port: 80
      targetPort: 8000
