apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gosty-worker
  name: gosty-worker
  namespace: gosty
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gosty-worker
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-worker
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: gosty-config
        image: 10.98.241.154/gosty-worker:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /live
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 3
        name: gosty-worker
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 3
---
