FROM alpine:3.13 AS gpac_builder

WORKDIR /app

RUN apk update && \
    apk add --no-cache \
        wget \
        g++ \
        make \
        git \
        && \
        git clone https://github.com/gpac/gpac.git

WORKDIR gpac

RUN ./configure --use-zlib=no && \
    JOB=$((2*$(nproc))) && \
    make -j $JOB && \
    mkdir -p install/bin && \
    cp -R ./bin/gcc ./install/lib && \
    rm ./install/lib/gm_* ./install/lib/*.a && \
    rm -Rf ./install/lib/temp && \
    mv ./install/lib/MP4* ./install/bin


FROM golang:1.16.0-alpine3.13

WORKDIR /app

COPY --from=gpac_builder /app/gpac/install/lib /usr/lib
COPY --from=gpac_builder /app/gpac/install/bin /usr/bin