FROM alpine:3.13

WORKDIR /app

# uncomment this to check when build context get bigger
#COPY . /tmp/build
#RUN find /tmp/build
ADD "http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?revision=1884511&view=co" /etc/mime.types
ADD ./build/apiserver/app .
ADD ./config.env .
RUN mkdir tmp

CMD ["./app"]