time gcloud beta container \
  --project "gosty-311908" \
  clusters create "gosty-k8s-cluster" \
   --zone "asia-southeast2-a" \
   --no-enable-basic-auth \
   --cluster-version "1.19.8-gke.1600" \
   --release-channel "regular" \
   --machine-type "e2-highcpu-2" \
   --image-type "COS_CONTAINERD" \
   --disk-type "pd-standard" \
   --disk-size "32" \
   --metadata disable-legacy-endpoints=true \
   --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
   --preemptible \
   --num-nodes "3" \
   --no-enable-stackdriver-kubernetes \
   --enable-ip-alias \
   --network "projects/gosty-311908/global/networks/default" \
   --subnetwork "projects/gosty-311908/regions/asia-southeast2/subnetworks/default" \
   --default-max-pods-per-node "110" \
   --no-enable-master-authorized-networks \
   --addons HttpLoadBalancing,GcePersistentDiskCsiDriver \
   --enable-autoupgrade \
   --enable-autorepair \
   --max-surge-upgrade 1 \
   --max-unavailable-upgrade 0 \
   --enable-shielded-nodes \
   --node-locations "asia-southeast2-a"
