apiVersion: v1
kind: ConfigMap
metadata:
  name: gosty-config
  namespace: gosty
data:
  MONGODB_USERNAME: "root"
  MONGODB_PASSWORD: "root"
  MONGODB_DATABASE: "gosty"
  MONGODB_TIMEOUT: "5"

  RABBITMQ_USERNAME: "username"
  RABBITMQ_PASSWORD: "password"

  FILE_MIN_SIZE_MB: "50"
  PING_WORKER_FAILURE_THRESHOLD: "10"

  FILESERVER_PEER_HOST: "gosty-fileserver-0,gosty-fileserver-1,gosty-fileserver-2"