apiVersion: v1
kind: Service
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  type: LoadBalancer
  selector:
    app: gosty-apiserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gosty-fileserver
  namespace: gosty
spec:
  type: LoadBalancer
  selector:
    app: gosty-fileserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: gosty-web
  namespace: gosty
spec:
  type: LoadBalancer
  selector:
    app: gosty-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
