apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gosty-web
  name: gosty-web
  namespace: gosty
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: gosty-web
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: topology.kubernetes.io/hostname
              weight: 100
      containers:
        - image: luqmansen/gosty-web:latest
          imagePullPolicy: Always
          name: gosty-web
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "50m"
              memory: "50m"
            limits:
              cpu: "256m"
              memory: "256Mi"

#apiVersion: v1
#kind: Service
#metadata:
#  name: gosty-web
#  namespace: gosty
#spec:
#  type: NodePort
#  selector:
#    app: gosty-web
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 30002
#
#---
