apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-external
  namespace: gosty
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: rabbit
    app.kubernetes.io/name: rabbitmq
  ports:
    - port: 15672
      name: rabbitmq-web
      targetPort: 15672
      nodePort: 30672
    - port: 5672
      name: rabbitmq-amqp
      targetPort: 5672
      nodePort: 31672