apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  template:
    spec:
      containers:
        - image: gosty-apiserver
          name: gosty-apiserver
          imagePullPolicy: Never
