apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gosty-fileserver
  namespace: gosty

spec:
  volumeClaimTemplates:
    - metadata:
        name: pv-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  template:
    spec:
      containers:
        - image: gosty-fileserver
          name: gosty-fileserver
          imagePullPolicy: Never



