apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-web
  namespace: gosty
spec:
  template:
    spec:
      containers:
        - name: gosty-web
          image: gosty-web
          imagePullPolicy: Never

