apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-worker
  namespace: gosty
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gosty-worker
          image: gosty-worker
          imagePullPolicy: Never

