apiVersion: apps/v1
kind: Deployment
metadata:
  name: gosty-apiserver
  namespace: gosty
spec:
  template:
    spec:
      containers:
        - image: localhost:5000/gosty-apiserver:latest
          name: gosty-apiserver
