apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gosty-fileserver-volume-claim
  namespace: gosty
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi