apiVersion: v1
kind: Service
metadata:
  name: gosty-fileserver
  namespace: gosty
spec:
  type: NodePort
  selector:
    app: gosty-fileserver
  ports:
    - port: 80
      targetPort: 8001
      nodePort: 30001
