apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gosty-fileserver
  name: gosty-fileserver
  namespace: gosty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosty-fileserver
  serviceName: gosty-fileserver
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-fileserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3s-node-01

      containers:
        - image: luqmansen/gosty-fileserver:latest
          name: gosty-fileserver
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: gosty-fileserver-volume
              mountPath: /app/storage

      volumes:
        - name: gosty-fileserver-volume
          persistentVolumeClaim:
            claimName: gosty-fileserver-volume-claim