apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gosty-fileserver
  name: gosty-fileserver
  namespace: gosty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gosty-fileserver
  serviceName: gosty-fileserver
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-fileserver
    spec:
      affinity:
        podAntiAffinity:
          #          requiredDuringSchedulingIgnoredDuringExecution:
          #            - topologyKey: topology.kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/hostname
      containers:
        - image: 192.168.56.1:5000/gosty-fileserver:latest
          name: gosty-fileserver
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: gosty-fileserver-hostpath
              mountPath: /app/storage

  volumeClaimTemplates:
    - metadata:
        name: gosty-fileserver-hostpath
      spec:
        accessModes:
          - "ReadWriteMany"
        resources:
          requests:
            storage: "5Gi"
---
