apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gosty-fileserver
  name: gosty-fileserver
  namespace: gosty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosty-fileserver
  serviceName: gosty-fileserver
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gosty-fileserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.kubernetes.io/hostname

      containers:
        - image: luqmansen/gosty-fileserver:latest
          name: gosty-fileserver
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: gosty-fileserver-volume
              mountPath: /app/storage


      volumes:
        - name: gosty-fileserver-volume
          persistentVolumeClaim:
            claimName: gosty-fileserver-volume-claim