name: Docker alpine-ffmpeg-mp4box CI

on:
  push:
    branches:
      - 'main'

jobs:
  alpine-ffmpeg-mp4box:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
            docker/Dockerfile-alpine-ffmpeg-mp4box

      - name: Display changed files
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"

      - name: Set up QEMU
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        if: steps.changed_files.outputs.files_changed == 'true'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile-alpine-ffmpeg-mp4box
          tags: luqmansen/alpine-ffmpeg-mp4box:latest

      - name: Image digest
        if: steps.changed_files.outputs.files_changed == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}