name: Docker gosty CI

on:
  push:
    branches:
      - 'main'

jobs:
  gosty-worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build worker
        run: |
          make cleanup
          make worker-bin

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-worker
          dockerfile: docker/Dockerfile-worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  gosty-fileserver:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build fileserver
        run: |
          make cleanup
          make fs-bin

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-fileserver
          dockerfile: docker/Dockerfile-fileserver
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  gosty-apiserver:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build apiserver
        run: |
          make cleanup
          make api-bin

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-apiserver
          dockerfile: docker/Dockerfile-apiserver
          tags: ${{ steps.get_version.outputs.VERSION }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}