name: Docker gosty-worker CI

on:
  push:
    branches:
      - 'main'

jobs:
  gosty-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build worker
        run: |
          make build-bin

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-worker
          dockerfile: docker/Dockerfile-worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
