name: Docker gosty-worker CI

on:
  push:
    branches:
      - 'main'

jobs:
  gosty-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build worker
        run: |
          ls -lah
          make build-bin

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/Dockerfile-worker
          tags: luqmansen/gosty-worker:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}