name: image build gosty component

on:
  push:
    branches:
      - 'main'

jobs:
  worker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Build worker
        run: |
          make cleanup
          make worker-bin

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-worker
          dockerfile: docker/Dockerfile-worker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  fileserver:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Build fileserver
        run: |
          make cleanup
          make fs-bin

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-fileserver
          dockerfile: docker/Dockerfile-fileserver
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

  apiserver:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Build apiserver
        run: |
          make cleanup
          make api-bin

      - name: Publish to Dockerhub
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: luqmansen/gosty-apiserver
          dockerfile: docker/Dockerfile-apiserver
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}